/* Palabras que acercan un término del glosario a una noción del traductor (solo para la aproximación
   «noción afín»; no alteran la búsqueda por nociones). Se comparan contra el término y su definición. */
export const AFINES = {
  relacion: ["transferenc", "contratransferenc", "encuadre", "rapport", "alianza", "ruptura", "reparacion", "setting", "base segura", "autorrevelacion", "dos personas", "vincular", "engaging", "ambito tu", "ambito nosotros", "dialogo", "inversion de roles", "role reversal", "modalidad preferida", "axiomas de la comunicacion", "comunicacion", "reparentaliz", "efecto dodo", "factores comunes"],
  defensa: ["defens", "represi", "negacion", "proyecc", "proyectiv", "disociac", "escision", "evitacion", "resistenc"],
  trauma: ["trauma", "abuso", "disociac", "maltrato"],
  self: ["yo ", "ello", "superyo", "self", "identidad", "ego", "yoic", "personalidad", "gestalt", "figura", "selfobjet", "marco de referencia", "campo fenomenal", "worldview", "perspectiva del mundo", "naturaleza humana", "fluir vital"],
  cambio: ["refuerz", "extincion", "castigo", "condicionamiento", "aprendizaje", "modelado", "cambio", "mecanismo de cambio", "habituacion", "control de estimulos", "generalizacion", "entrenamiento", "generacion de soluciones", "autorregulacion", "habla privada", "operaciones motivadoras", "mando", "tacto", "respuesta controlad", "determinismo reciproco", "interconductual", "disposicionales", "adaptacion", "evocacion", "efectividad", "ajuste", "matching"],
  pensamiento: ["esquema", "cognici", "creenci", "distorsion", "pensamiento", "interpretacion", "atribucion"],
  emocion: ["emocion", "afecto", "sentimiento", "arousal", "activacion"],
  libertad: ["autonom", "agencia", "empodera", "autodetermin", "libertad", "responsabilidad", "eleccion", "autoeficacia"],
  cultura: ["feminis", "patriarc", "opresion", "genero", "poder", "politic", "cultural", "saberes", "hegemon"],
  sentido: ["espiritu", "trascend", "proposito", "significado", "sentido", "valores", "logos", "cuarta fuerza", "holoarquia", "investigacion filosofica", "intencionalidad", "aperturidad", "diferenciacion"],
  mindfulness: ["awareness", "darse cuenta", "conciencia", "presente", "flujo", "flow", "contacto", "atencion", "aceptacion", "experienciar", "focusing", "apertura horizontal"],
  esperanza: ["resilien", "fortaleza", "optimism", "bienestar", "esperanza", "florecer"],
  diagnostico: ["psicopatolog", "desajuste", "trastorno", "evaluacion", "formulacion", "diagnost"],
  meta: ["funcionamiento pleno", "autorrealiz", "crecimiento", "objetivo", "salud mental", "individuacion"],
  conflicto: ["polaridad", "dilema", "contradic", "paradoj", "ambivalenc", "conflicto", "complejo", "triangulac"],
  cuerpo: ["energet", "bloqueo", "somatic", "respirac", "corporal", "cuerpo", "organismic", "fisiolog"],
  inconsciente: ["inconscien", "ello", "arquetip", "sincronicidad", "perinatal", "matriz", "sombra", "lo real", "real lacan", "lacan"],
  motivacion: ["motivacion", "deseo", "necesidad", "pulsion", "impulso", "voluntad"],
  apego: ["apego", "vinculo", "dependencia", "intimidad", "mutualidad", "relacion igualitaria", "contexto relacional", "base segura", "seguridad frente", "busqueda de seguridad"],
  empatia: ["empati", "compasion", "sintonia", "aceptacion incondicional", "reflejo", "colaboracion"],
  sintoma: ["sintoma", "malestar", "problema", "funcion del sintoma"],
  resistencia: ["resistenc", "reactancia", "desafiante", "oposicion"],
  duelo: ["duelo", "perdida", "luto"],
  culpa: ["culpa", "verguenza", "remordimiento", "inautentic"],
  autoestima: ["autoestima", "valia", "autoconcepto", "autoimagen"],
  ansiedad: ["ansiedad", "angustia", "miedo", "fobia", "panico"],
  depresion: ["depres", "tristeza", "anhedonia"],
  sueno: ["sueno", "onirico", "imaginacion activa"],
};
